# Generated by Django 4.2 on 2025-02-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nesta.org.uk%2Fproject%2Fdigital-marketing-and-teenage-health%2F&psig=AOvVaw0ksTwwdXucusl1JDfNpGey&ust=1739237987608000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNDOocv8t4sDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
